spring.application.name=QuantumSpringBoot
spring.docker.compose.enabled=false
spring.datasource.url=${SPRING_DATASOURCE.URL}
spring.datasource.driverClassName=${SPRING_DATASOURCE_DRIVERCLASSNAME}
spring.datasource.username=${SPRING_DATASOURCE.USERNAME}
spring.datasource.password=${SPRING_DATASOURCE.PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
jwt.secret=${JWT.SECRET}
spring.flyway.enabled=true
spring.flyway.locations=classpath:db.migration
#spring.flyway.baseline-on-migrate=true
#debug=true
AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
AWS_REGION=${AWS_REGION}
aws.s3.bucket=${AWS.S3.BUCKET}
file.upload-dir=.
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
storage.type=${STORAGE_TYPE}